name = "cw4b2"
main = "src/index.ts"
compatibility_date = "2023-03-24"
[triggers]
crons = ["17 4 * * 2"] # 设置每周一凌晨4点17分更新 Backblaze B2 Worker

[vars]
# The necessary secrets are:
# - BUCKET_ID
# - BUCKET_NAME
# - BUCKET_AUTHORIZATION
# - CLOUDFLARE_ACCOUNT_ID
# - CLOUDFLARE_API_TOKEN
